apiVersion: v1
kind: Namespace
metadata:
  name: nas
---
apiVersion: v1
kind: Service
metadata:
  name: nas-service
  namespace: nas
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas-service
  namespace: nas
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - name: http
        port: 5000