apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: web-gateway
  namespace: gateway
spec:
  gatewayClassName: nginx
  listeners:
    # Blog
    - name: http-blog
      protocol: HTTP
      port: 80
      hostname: blog.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-blog
      protocol: HTTPS
      port: 443
      hostname: blog.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: blog-sonhs-com-tls

    # Nas
    - name: http-www
      protocol: HTTP
      port: 80
      hostname: www.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-www
      protocol: HTTPS
      port: 443
      hostname: www.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: www-sonhs-com-tls

    - name: http
      protocol: HTTP
      port: 80
      hostname: sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https
      protocol: HTTPS
      port: 443
      hostname: sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: sonhs-com-tls

    # Climbear-server
    - name: http-climbear
      protocol: HTTP
      port: 80
      hostname: climbear.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-climbear
      protocol: HTTPS
      port: 443
      hostname: climbear.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: climbear-sonhs-com-tls

    # Chocoletter Client
    - name: http-chocoletter
      protocol: HTTP
      port: 80
      hostname: chocoletter.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-chocoletter
      protocol: HTTPS
      port: 443
      hostname: chocoletter.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: chocoletter-sonhs-com-tls

    # Chocoletter Client-After
    - name: http-chocoletter-after
      protocol: HTTP
      port: 80
      hostname: chocoletter-after.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-chocoletter-after
      protocol: HTTPS
      port: 443
      hostname: chocoletter-after.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: chocoletter-after-sonhs-com-tls

    # Chocoletter Server
    - name: http-chocoletter-server
      protocol: HTTP
      port: 80
      hostname: chocoletter-server.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-chocoletter-server
      protocol: HTTPS
      port: 443
      hostname: chocoletter-server.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: chocoletter-server-sonhs-com-tls

    # Chocoletter Server-After
    - name: http-chocoletter-server-after
      protocol: HTTP
      port: 80
      hostname: chocoletter-server-after.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

#    - name: https-chocoletter-server-after
#      protocol: HTTPS
#      port: 443
#      hostname: chocoletter-server-after.sonhs.com
#      allowedRoutes:
#        namespaces:
#          from: All
#      tls:
#        mode: Terminate
#        certificateRefs:
#          - kind: Secret
#            name: chocoletter-server-after-sonhs-com-tls

    # Chocoletter Chat
    - name: http-chocoletter-chat
      protocol: HTTP
      port: 80
      hostname: chocoletter-chat.sonhs.com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-chocoletter-chat
      protocol: HTTPS
      port: 443
      hostname: chocoletter-chat.sonhs.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: chocoletter-chat-sonhs-com-tls